### ISSUE TITLE
gotk bootstrap

### ISSUE THREAD

**Issue by nvanheuverzwijn** [fluxcd/toolkit#264] opened 2020-09-22 21:04 UTC
When issuing `gotk bootstrap github --components=source-controller,helm-controller,notification-controller --path=staging --version=latest --owner=redacted --repository=redacted` this error comes up 

`error: unable to recognize "/tmp/gitops-system984688183/unstable/gitops-system/toolkit-kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1alpha1"`

Notice, I removed `kustomize-controller` from the `--components` option.

Using the default works.

**Comment by stefanprodan** [comment] 2020-09-22 21:26
Duplicate of #252

**Closed by stefanprodan** 2020-09-22 21:26 UTC
